# Generated by Django 5.1.3 on 2024-11-11 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ownsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user',
            new_name='User',
        ),
    ]
