# Generated by Django 5.1.3 on 2024-11-11 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ownsite', '0003_remove_contact_user_alter_contact_is_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='updated_at',
        ),
    ]
